config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :api_translators
  end
  namespace :admin do
    resources :configuration_identifiers
  end
  namespace :admin do
    resources :currencies
  end

  devise_for :users

  post 'configurator/ids=:ids', to: 'configurator#items_to_cart'

  get 'configurator', to: 'configurator#configurator'

  get 'configurator/show_offer/offer_products=:offer_products', to: 'configurator#show'

  resources :order_items, only: [:create, :update, :destroy]

  get 'cart/sale_id=:sale_id', to: 'carts#sale'

  resource :cart

  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :sales

    controller :product_features do
      get 'product_features/product=:product', to: 'product_features#index'
      get 'product_features/product=:product/page=:page', to: 'product_features#index'
      resources :product_features
    end

    resources :extract_xmls do
      post :extract_xml_file, on: :member
      post :update_products, on: :member
      get  :delete_all_products, on: :collection
    end

    get '', to: 'admin#admin'
    get '/:product', to: 'products#index'

    resources :products
  end

  resources :store_mcomputers

  controller 'store_mcomputers' do
    get '/search/', to: 'store_mcomputers#list'
    get '/product=:product', to: 'store_mcomputers#list'
    get '/product=:product/filter=:filter', to: 'store_mcomputers#list'
    get '/product=:product/page=:page', to: 'store_mcomputers#list'
  end

  root 'store_mcomputers#store_mcomputers'
end

app/models/admin/product_feature.rb
class Admin::ProductFeature < ActiveRecord::Base

  has_many :order_items
  #default_scope { where(active: true) }

  validates :category_id, :description, presence: true
            # :sub_category_id, :identifier, :description
            # validates :category_id, presence: true
end

app/controllers/admin/product_features_controller.rb
class Admin::ProductFeaturesController < Admin::AdminController
    before_action :set_admin_product_feature, only: [:show, :edit, :update, :destroy]

    def index
      @page = params[:page]
      @product_param = params[:product]
      @products_all = Admin::ProductFeature.where(identifier: @product_param)

      product_num = 21
      num_all_productsts = @products_all.count
      @pages = num_all_productsts / product_num
      @products = @products_all

      if !@page.nil? && !@product_param.nil?
        @admin_product_features = @products_all.limit(product_num).offset(@page.to_i < 0 || @page.to_i > @pages ? 0 : @page)
      elsif !@product_param.nil?
        @admin_product_features = @products_all.limit(product_num).offset(0)
      else
        @admin_product_features = Admin::ProductFeature.all
      end
    end

    def show
    end

    def new
      @admin_product_feature = Admin::ProductFeature.new
    end

    def create
      #render text: admin_product_feature_params
      data = admin_product_feature_params.deep_symbolize_keys
      @admin_product_feature = Admin::ProductFeature.create(data)
      if @admin_product_feature.errors.empty?
        flash[:notice] = "Product successfully created!"
        redirect_to action: 'index', product: data[:identifier]
      else
        flash[:notice] = "You made mistakes in your form! Please correct them"
        render 'new'
      end
    end

    def edit
    end

    def update
      data = admin_product_feature_params.deep_symbolize_keys
      @admin_product_feature.update(data)
      if @admin_product_feature.errors.empty?
        flash[:notice] = "Product successfully updated!"
        redirect_to action: 'index', product: data[:identifier]
      else
        flash[:error] = "You made mistakes in your form! Please correct them"
        render :edit
      end
    end

    def destroy
      @admin_product_feature.delete
      flash[:notice] = "Product successfully deleted!"
      redirect_to :back
    end

    def set_admin_product_feature
      @admin_product_feature = Admin::ProductFeature.find(params[:id])
    end

    def admin_product_feature_params
      if params[:admin_product][:description].is_a?(Hash)
        params.require(:admin_product_feature).permit(:category_id, :sub_category_id, :identifier).tap do |whitelisted|
          whitelisted[:description] = Hash params[:admin_product][:description].deep_symbolize_keys
        end
      else
        params.require(:admin_product_feature).permit(:category_id, :sub_category_id, :identifier).tap do |whitelisted|
          whitelisted[:description] = params[:admin_product][:description]
        end
      end
    end
end

app/helpers/admin/product_features_helper.rb
module Admin::ProductFeaturesHelper
end

app/views/admin/product_features/_form.html.erb
<%= form_for(@admin_product_feature) do |f| %>
  <% if @admin_product_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product_feature.errors.count, "error") %> prohibited this admin_product_feature from being saved:</h2>

      <ul>
      <% @admin_product_feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :sub_category_id %><br>
    <%= f.number_field :sub_category_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/product_features/edit.html.erb
<h4>Editing Product</h4>



<%= link_to 'Show', @admin_product_feature %> |
<%= link_to 'Back', admin_product_features_path %>

<style>
    .basic-grey {
        margin-left:auto;
        margin-right:auto;
        max-width: 100%;
        background: #F7F7F7;
        padding: 25px 15px 25px 10px;
        font: 16px Georgia, "Times New Roman", Times, serif;
        color: #888;
        text-shadow: 1px 1px 1px #FFF;
        border:1px solid #E4E4E4;
    }
    .basic-grey h1 {
        font-size: 25px;
        padding: 0px 0px 10px 40px;
        display: block;
        border-bottom:1px solid #E4E4E4;
        margin: -10px -15px 30px -10px;;
        color: #888;
    }
    .basic-grey h1>span {
        display: block;
        font-size: 16px;
    }
    .basic-grey label {
        display: block;
        margin: 0px;
    }
    .basic-grey label>span {
        float: left;
        width: 20%;
        text-align: right;
        padding-right: 10px;
        margin-top: 10px;
        color: #888;
    }
    .basic-grey input[type="text"], .basic-grey input[type="email"], .basic-grey textarea, .basic-grey select {
        border: 1px solid #DADADA;
        color: #888;
        height: 30px;
        margin-bottom: 16px;
        margin-right: 6px;
        margin-top: 2px;
        outline: 0 none;
        padding: 3px 3px 3px 5px;
        width: 70%;
        font-size: 16px;
        line-height:15px;
        box-shadow: inset 0px 1px 4px #ECECEC;
        -moz-box-shadow: inset 0px 1px 4px #ECECEC;
        -webkit-box-shadow: inset 0px 1px 4px #ECECEC;
    }
    .basic-grey textarea{
        padding: 5px 3px 3px 5px;
    }
    .basic-grey select {
        background: #FFF url('down-arrow.png') no-repeat right;
        background: #FFF url('down-arrow.png') no-repeat right);
        appearance:none;
        -webkit-appearance:none;
        -moz-appearance: none;
        text-indent: 0.01px;
        text-overflow: '';
        width: 70%;
        height: 35px;
        line-height: 25px;
    }
    .basic-grey textarea{
        height:100px;
    }
    .basic-grey .button {
        background: #E27575;
        border: none;
        padding: 10px 25px 10px 25px;
        color: #FFF;
        box-shadow: 1px 1px 5px #B6B6B6;
        border-radius: 3px;
        text-shadow: 1px 1px 1px #9E3F3F;
        cursor: pointer;
    }
    .basic-grey .button:hover {
        background: #CF7A7A
    }
</style>

<div class="container">
<div class="basic-grey">
  <%= form_for(@admin_product_feature) do |f| %>
      <% if @admin_product_feature.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@admin_product_feature.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

            <ul>

              <% @admin_product_feature.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>

            </ul>

          </div>
      <% end %>

      <label>
        <span>Категория:</span>
        <%= f.collection_select(:category_id, Admin::Category.all, :id, :name_cat, :prompt => "Select Category") %>
      </label>

      <label>
        <span>Продукт:</span>
        <%= f.collection_select(:sub_category_id, Admin::SubCategory.all, :id, :name, :prompt => "Select Product") %>
      </label>

      <label>
        <span>Identifier:</span>
        <%=f.collection_select(:identifier, Admin::SubCategory.all, :identifier, :identifier, :prompt => "Select Identifier") %>
      </label>

      <% desription = eval(@admin_product_feature['description']) %>

      <% desription.each do |key_1, val_1| %>
          <br>
          <% if val_1.is_a?(Hash)  %>
              <% val_1.each do |key_2, val_2| %>

                  <% if val_2.is_a?(Hash)  %>
                      <% val_2.each do |value_h| %>
                          <label>
                              <span><%= val_2 %>:</span>
                              <input type="text" name="admin_product[description][<%= key_1 %>][<%= key_2 %>][<%= value_h.each{|k,v| k}.first %>]" value="<%= value_h.each{|k,v| v}.last %>" id="admin_product_description" class="label-values"/>
                          </label>
                      <% end %>
                  <% elsif val_2.is_a?(Array)  %>
                      <% i = 0 %>
                      <% val_2.each do |value_a| %>
                          <label>
                              <input style="width: 200px" type="text" name="admin_product[description][<%= key_1 %>][<%= key_2 %>][<%= value_a[i] %>][<%= value_a.map { |k,| k }.first %>]" value="<%= value_a.map { |k, v| v }.first %>" id="admin_product_description" class="label-names"/>
                              <input type="text" name="admin_product[description][<%= key_1 %>][<%= key_2 %>][<%= value_a[i] %>][<%= value_a.map { |k,| k }.last %>]" value="<%= value_a.map { |k, v| v }.last.squish %>" id="admin_product_description" class="label-values"/>
                              <% i += 1 %>
                          </label>
                      <% end %>
                  <% end %>

              <% end %>
          <% else %>
              <label>
              <span><%= key_1 %>:</span>

              <% if key_1[/general_description/] %>
                  <textarea class="form-control" rows="20"  name="admin_product[description][<%= key_1 %>]" id="admin_product_description"><%= val_1 %></textarea>
              <% else %>
                  <input type="text" name="admin_product[description][<%= key_1 %>]" value="<%= val_1 %>" id="admin_product_description" class="label-values"/>
              <% end %>
          <% end %>
          </label>
      <% end %>

      <div class="actions">
        <%= f.submit class: "btn btn-default"%>
      </div>

  <% end %>
  </div>
</div>

app/views/admin/product_features/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Продукти</h3>
<%= link_to 'Нов продукт', new_admin_product_feature_path %>

<%= render "admin/admin_shared/admin_pagination" %>

<table class = "table table-bordered table-striped" >
  <thead>
    <tr>
      <th>Category ID</th>
      <th>Category</th>
      <th>Product ID</th>
      <th>Product</th>
      <th>Identifier</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_product_features.each do |admin_product_feature| %>
      <tr>
        <td><%= admin_product_feature.category_id %></td>
        <td> <%= Admin::Category.where(id: admin_product_feature.category_id).first.name_cat %></td>
        <td><%= admin_product_feature.sub_category_id %></td>
        <td> <%= Admin::SubCategory.where(id: admin_product_feature.sub_category_id).first.name %></td>
        <td> <%= admin_product_feature.identifier %></td>
        <td>

           <% #eval(@products.description).deep_symbolize_keys%>
          <% descript_product = eval(admin_product_feature.description) %>
            <ul style="list-style-type: none">
              <li><%= descript_product[:id] %></li>
              <li><%= descript_product[:code] %></li>
              <li><%= descript_product[:product_status] %></li>
              <li><strong><%= descript_product[:price] %></strong> <%= descript_product[:currency] %> </li>
            </ul>
        </td>


        <td><%= link_to 'Show', admin_product_feature %></td>
        <td><%= link_to 'Edit', edit_admin_product_feature_path(admin_product_feature) %></td>
        <td><%= link_to 'Destroy', admin_product_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render "admin/admin_shared/admin_pagination" %>

app/views/admin/product_features/new.html.erb
<h4>New Product</h4>

<style>
    .basic-grey {
        margin-left:auto;
        margin-right:auto;
        max-width: 100%;
        background: #F7F7F7;
        padding: 25px 15px 25px 10px;
        font: 16px Georgia, "Times New Roman", Times, serif;
        color: #888;
        text-shadow: 1px 1px 1px #FFF;
        border:1px solid #E4E4E4;
    }
    .basic-grey h1 {
        font-size: 25px;
        padding: 0px 0px 10px 40px;
        display: block;
        border-bottom:1px solid #E4E4E4;
        margin: -10px -15px 30px -10px;;
        color: #888;
    }
    .basic-grey h1>span {
        display: block;
        font-size: 16px;
    }
    .basic-grey label {
        display: block;
        margin: 0px;
    }
    .basic-grey label>span {
        float: left;
        width: 20%;
        text-align: right;
        padding-right: 10px;
        margin-top: 10px;
        color: #888;
    }
    .basic-grey input[type="text"], .basic-grey input[type="email"], .basic-grey textarea, .basic-grey select {
        border: 1px solid #DADADA;
        color: #888;
        height: 30px;
        margin-bottom: 16px;
        margin-right: 6px;
        margin-top: 2px;
        outline: 0 none;
        padding: 3px 3px 3px 5px;
        width: 70%;
        font-size: 16px;
        line-height:15px;
        box-shadow: inset 0px 1px 4px #ECECEC;
        -moz-box-shadow: inset 0px 1px 4px #ECECEC;
        -webkit-box-shadow: inset 0px 1px 4px #ECECEC;
    }
    .basic-grey textarea{
        padding: 5px 3px 3px 5px;
    }
    .basic-grey select {
        appearance:none;
        -webkit-appearance:none;
        -moz-appearance: none;
        text-indent: 0.01px;
        text-overflow: '';
        width: 70%;
        height: 35px;
        line-height: 25px;
    }
    .basic-grey textarea{
        height:100px;
    }
    .basic-grey .button {
        background: #E27575;
        border: none;
        padding: 10px 25px 10px 25px;
        color: #FFF;
        box-shadow: 1px 1px 5px #B6B6B6;
        border-radius: 3px;
        text-shadow: 1px 1px 1px #9E3F3F;
        cursor: pointer;
    }
    .basic-grey .button:hover {
        background: #CF7A7A
    }
</style>


<%= link_to 'Show', @admin_product_feature %> |
<%= link_to 'Back', admin_product_features_path %>

<div class="container">
    <div class="basic-grey">
  <%= form_for(@admin_product_feature) do |f| %>
      <% if @admin_product_feature.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@admin_product_feature.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

            <ul>
              <% @admin_product_feature.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>

          </div>
      <% end %>

      <label>
        <span>Категория:</span>
        <%= f.collection_select(:category_id, Admin::Category.all, :id, :name_cat, :prompt => "Select Category") %>
      </label>

      <label>
        <span>Продукт:</span>
        <%= f.collection_select(:sub_category_id, Admin::SubCategory.all, :id, :name, :prompt => "Select Product") %>
      </label>

      <label>
        <span>Identifier:</span>
        <%=f.collection_select(:identifier, Admin::SubCategory.all, :identifier, :identifier, :prompt => "Select Identifier") %>
      </label>


          <label>
            <span>Article id:</span>
            <input type="text" name="admin_product[description][aricle_id]" value="" id="admin_product_description" class="label-values"/>
          </label>

      <label>
          <span>Name product:</span>
          <input type="text" name="admin_product[description][code]" value="" id="admin_product_description" class="label-values"/>
      </label>

          <label>
            <span>Product status:</span>
            <input type="text" name="admin_product[description][product_status]" value="" id="admin_product_description" class="label-values"/>
          </label>

          <label>
            <span>Product description</span>
            <input type="text" name="admin_product[description][general_description]" value="" id="admin_product_description" class="label-values"/>
          </label>

          <label>
            <span>Price:</span>
            <input type="text" name="admin_product[description][price]" value="" id="admin_product_description" class="label-values"/>
          </label>

          <label>
            <span>Currency:</span>
            <input type="text" name="admin_product[description][currency]" value="" id="admin_product_description" class="label-values"/>
          </label>

          <label>
            <span>Basic image</span>
            <input type="text" name="admin_product[description][main_picture_url]" value="" id="admin_product_description" class="label-values"/>
          </label>

          <div class="input_fields_wrap">
            <button class="add_field_button">Add gallery</button>
            <div>
              <label>
                <span>Product galery:</span>
                <input type="text" name="admin_product[description][gallery][picture][][picture_url]">
              </label>
            </div>
          </div>

          <div class="specification_fields_wrap">
            <button class="add_spec_field_button">Add specification</button>
            <div>
              <label>
                <input style="width: 200px" type="text" name="admin_product[description][properties][property][][name]" id="admin_product_description" class="label-names">
                <input type="text" name="admin_product[description][properties][property][][text]" id="admin_product_description" class="label-values">
              </label>
            </div>
          </div>

          <div class="actions">
        <%= f.submit class: "btn btn-default"%>
      </div>

  <% end %>
</div>
</div>
<script>

    $(document).ready(function() {
        var max_fields      = 20; //maximum input boxes allowed
        var wrapper         = $(".specification_fields_wrap"); //Fields wrapper
        var add_button      = $(".add_spec_field_button"); //Add button ID
        var x = 1; //initlal text box count

        $(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append(
                        '<div class="fields" ><label>' +
                        '<input style="width: 200px" type="text" name="admin_product[description][properties][property][][name]" id="admin_product_description" class="label-names">' +
                        '  <input type="text" name="admin_product[description][properties][property][][text]" id="admin_product_description" class="label-values">' +
                        '<a href="#" class="remove_field">Remove</a>' +
                        '</label></div>'); //add input box
            }
        });

        $(wrapper).on("click", ".remove_field", function(e){ //user click on remove text
            e.preventDefault(); $(this).parent('div.fields label').remove(); x--;
        })
    });


    $(document).ready(function() {
        var max_fields      = 5; //maximum input boxes allowed
        var wrapper         = $(".input_fields_wrap"); //Fields wrapper
        var add_button      = $(".add_field_button"); //Add button ID
        var x = 1; //initlal text box count

        $(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
            $(wrapper).append(
                    '<div class="fields" ><label><span>Product galery:</span>' +
                    '<input type="text" name="admin_product[description][gallery][picture][][picture_url]"/>' +
                    '<a href="#" class="remove_field">Remove</a>' +
                    '</label></div>'); //add input box
            }
        });

        $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
            e.preventDefault(); $(this).parent('div.fields label').remove(); x--;
        })
    });

</script>

app/views/admin/product_features/show.html.erb
<style>

    table#acrylic {
        border-collapse: separate;
        background: #fff;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        margin: 50px auto;
        -moz-box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
        -webkit-box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
        cursor: pointer;
    }

    #acrylic thead {
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
    }

    #acrylic thead th {
        font-family: 'Roboto';
        font-size: 16px;
        font-weight: 400;
        color: #fff;
        text-shadow: 1px 1px 0px rgba(0, 0, 0, 0.5);
        text-align: left;
        padding: 20px;
        background-size: 100%;
        background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #646f7f), color-stop(100%, #4a5564));
        background-image: -moz-linear-gradient(#646f7f, #4a5564);
        background-image: -webkit-linear-gradient(#646f7f, #4a5564);
        background-image: linear-gradient(#646f7f, #4a5564);
        border-top: 1px solid #858d99;
    }

    #acrylic thead th:first-child {
        -moz-border-top-right-radius: 5px;
        -webkit-border-top-left-radius: 5px;
        border-top-left-radius: 5px;
    }

    #acrylic thead th:last-child {
        -moz-border-top-right-radius: 5px;
        -webkit-border-top-right-radius: 5px;
        border-top-right-radius: 5px;
    }

    #acrylic tbody tr td {
        font-family: 'Open Sans', sans-serif;
        font-weight: 400;
        color: #5f6062;
        font-size: 13px;
        padding: 20px 20px 20px 20px;
        border-bottom: 1px solid #e0e0e0;
    }

    #acrylic tbody tr:nth-child(2n) {
        background: #f0f3f5;
    }

    #acrylic tbody tr:last-child td {
        border-bottom: none;
    }

    #acrylic tbody tr:last-child td:first-child {
        -moz-border-bottom-right-radius: 5px;
        -webkit-border-bottom-left-radius: 5px;
        border-bottom-left-radius: 5px;
    }

    #acrylic tbody tr:last-child td:last-child {
        -moz-border-bottom-right-radius: 5px;
        -webkit-border-bottom-right-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    #acrylic tbody:hover > tr td {
        filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=50);
        opacity: 0.5;
    }

    #acrylic tbody:hover > tr:hover td {
        text-shadow: none;
        color: #2d2d2d;
        filter: progid: DXImageTransform.Microsoft.Alpha(enabled=false);
        opacity: 1;
        transition: 0.2s all;
    }

</style>

<% product = eval(@admin_product_feature.description).deep_symbolize_keys %>

<h1><%= product[:code] %></h1>



<div class="container">
  <div class="row">
    <div class="col-xs-4 item-photo">
      <img style="max-width:100%;" src="<%= product[:main_picture_url]%>" />
    </div>
    <div class="col-xs-5" style="border:0px solid gray">
      <!-- Datos del vendedor y titulo del producto -->
      <h3><%= product[:code] %></h3>

      <h3 style="margin-top:0px;"><%= product[:price] %> <%= product[:currency] %></h3>

        <div>
          <ul>
            <% product[:properties][:property].each do |property| %>
                <li><strong><%= property[:name]%>:</strong> <%= property[:text]%></li>
            <% end %>
          </ul>
        </div>
      </div>

    <div class="col-xs-9">
      <ul class="menu-items">
        <p class="group inner list-group-item-text">
          <%= product[:general_description] %>
        </p>
      </ul>
      <div style="width:100%;border-top:1px solid silver">
        <p style="padding:15px;">
        <h3>
          Specification
        </h3>
        </p>
        <small>
          <table  id="acrylic">
            <thead>
            <tr>
              <th>Names</th>
              <th>Values</th>
            </tr>

            </thead>
            <% product[:properties][:property].each do |property| %>
                <tr>
                  <td><%= property[:name] %></td>  <td><%=  property[:text] %></td>
                </tr>
            <% end %>

          </table>
        </small>
      </div>
    </div>
  </div>
</div>