config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :api_translators
  end
  namespace :admin do
    resources :configuration_identifiers
  end
  namespace :admin do
    resources :currencies
  end

  devise_for :users

  post 'configurator/ids=:ids', to: 'configurator#items_to_cart'

  get 'configurator', to: 'configurator#configurator'

  get 'configurator/show_offer/offer_products=:offer_products', to: 'configurator#show'

  resources :order_items, only: [:create, :update, :destroy]

  get 'cart/sale_id=:sale_id', to: 'carts#sale'

  resource :cart

  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :sales

    controller :product_features do
      get 'product_features/product=:product', to: 'product_features#index'
      get 'product_features/product=:product/page=:page', to: 'product_features#index'
      resources :product_features
    end

    resources :extract_xmls do
      post :extract_xml_file, on: :member
      post :update_products, on: :member
      get  :delete_all_products, on: :collection
    end

    get '', to: 'admin#admin'
    get '/:product', to: 'products#index'

    resources :products
  end

  resources :store_mcomputers

  controller 'store_mcomputers' do
    get '/search/', to: 'store_mcomputers#list'
    get '/product=:product', to: 'store_mcomputers#list'
    get '/product=:product/filter=:filter', to: 'store_mcomputers#list'
    get '/product=:product/page=:page', to: 'store_mcomputers#list'
  end

  root 'store_mcomputers#store_mcomputers'
end

app/models/admin/configuration_identifier.rb
class Admin::ConfigurationIdentifier < ActiveRecord::Base
end

app/controllers/admin/configuration_identifiers_controller.rb
class Admin::ConfigurationIdentifiersController < ApplicationController
  before_action :set_admin_configuration_identifier, only: [:show, :edit, :update, :destroy]

  # GET /admin/configuration_identifiers
  # GET /admin/configuration_identifiers.json
  def index
    @admin_configuration_identifiers = Admin::ConfigurationIdentifier.all
  end

  # GET /admin/configuration_identifiers/1
  # GET /admin/configuration_identifiers/1.json
  def show
  end

  # GET /admin/configuration_identifiers/new
  def new
    @admin_configuration_identifier = Admin::ConfigurationIdentifier.new
  end

  # GET /admin/configuration_identifiers/1/edit
  def edit
  end

  # POST /admin/configuration_identifiers
  # POST /admin/configuration_identifiers.json
  def create
    @admin_configuration_identifier = Admin::ConfigurationIdentifier.new(admin_configuration_identifier_params)

    respond_to do |format|
      if @admin_configuration_identifier.save
        format.html { redirect_to @admin_configuration_identifier, notice: 'Configuration identifier was successfully created.' }
        format.json { render :show, status: :created, location: @admin_configuration_identifier }
      else
        format.html { render :new }
        format.json { render json: @admin_configuration_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/configuration_identifiers/1
  # PATCH/PUT /admin/configuration_identifiers/1.json
  def update
    respond_to do |format|
      if @admin_configuration_identifier.update(admin_configuration_identifier_params)
        format.html { redirect_to @admin_configuration_identifier, notice: 'Configuration identifier was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_configuration_identifier }
      else
        format.html { render :edit }
        format.json { render json: @admin_configuration_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/configuration_identifiers/1
  # DELETE /admin/configuration_identifiers/1.json
  def destroy
    @admin_configuration_identifier.destroy
    respond_to do |format|
      format.html { redirect_to admin_configuration_identifiers_url, notice: 'Configuration identifier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_configuration_identifier
      @admin_configuration_identifier = Admin::ConfigurationIdentifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_configuration_identifier_params
      params.require(:admin_configuration_identifier).permit(:identifier)
    end
end

app/helpers/admin/configuration_identifiers_helper.rb
module Admin::ConfigurationIdentifiersHelper
end

app/views/admin/configuration_identifiers/_form.html.erb
<%= form_for(@admin_configuration_identifier) do |f| %>
  <% if @admin_configuration_identifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_configuration_identifier.errors.count, "error") %> prohibited this admin_configuration_identifier from being saved:</h2>

      <ul>
      <% @admin_configuration_identifier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.text_area :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/configuration_identifiers/edit.html.erb
<h1>Editing Admin Configuration Identifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_configuration_identifier %> |
<%= link_to 'Back', admin_configuration_identifiers_path %>

app/views/admin/configuration_identifiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Configuration Identifiers</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_configuration_identifiers.each do |admin_configuration_identifier| %>
      <tr>
        <td><%= admin_configuration_identifier.identifier %></td>
        <td><%= link_to 'Show', admin_configuration_identifier %></td>
        <td><%= link_to 'Edit', edit_admin_configuration_identifier_path(admin_configuration_identifier) %></td>
        <td><%= link_to 'Destroy', admin_configuration_identifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration identifier', new_admin_configuration_identifier_path %>

app/views/admin/configuration_identifiers/new.html.erb
<h1>New Admin Configuration Identifier</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_configuration_identifiers_path %>

app/views/admin/configuration_identifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @admin_configuration_identifier.identifier %>
</p>

<%= link_to 'Edit', edit_admin_configuration_identifier_path(@admin_configuration_identifier) %> |
<%= link_to 'Back', admin_configuration_identifiers_path %>