config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :api_translators
  end
  namespace :admin do
    resources :configuration_identifiers
  end
  namespace :admin do
    resources :currencies
  end

  devise_for :users

  post 'configurator/ids=:ids', to: 'configurator#items_to_cart'

  get 'configurator', to: 'configurator#configurator'

  get 'configurator/show_offer/offer_products=:offer_products', to: 'configurator#show'

  resources :order_items, only: [:create, :update, :destroy]

  get 'cart/sale_id=:sale_id', to: 'carts#sale'

  resource :cart

  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :sales

    controller :product_features do
      get 'product_features/product=:product', to: 'product_features#index'
      get 'product_features/product=:product/page=:page', to: 'product_features#index'
      resources :product_features
    end

    resources :extract_xmls do
      post :extract_xml_file, on: :member
      post :update_products, on: :member
      get  :delete_all_products, on: :collection
    end

    get '', to: 'admin#admin'
    get '/:product', to: 'products#index'

    resources :products
  end

  resources :store_mcomputers

  controller 'store_mcomputers' do
    get '/search/', to: 'store_mcomputers#list'
    get '/product=:product', to: 'store_mcomputers#list'
    get '/product=:product/filter=:filter', to: 'store_mcomputers#list'
    get '/product=:product/page=:page', to: 'store_mcomputers#list'
  end

  root 'store_mcomputers#store_mcomputers'
end

app/models/admin/sub_category.rb
class Admin::SubCategory < ActiveRecord::Base
  validates :category_id, :name, :identifier, presence: true
end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < Admin::AdminController
  before_action :set_admin_sub_category, only: [:show, :edit, :update, :destroy]

  def index
    @admin_sub_categories = Admin::SubCategory.all
  end

  def show
  end

  def new
    @admin_sub_category = Admin::SubCategory.new
  end

  def create
    @admin_sub_category = Admin::SubCategory.create(admin_sub_category_params)
    if @admin_sub_category.errors.empty?
      flash[:notice] = "Product name successfully created!"
      redirect_to admin_sub_categories_path(@admin_sub_category)
    else
      flash.now[:error] = "Product name is not created!"
      render 'new'
    end
  end

  def edit
  end

  def update
    @admin_sub_category.update(admin_sub_category_params)
    if @admin_sub_category.errors.empty?
      flash[:notice] = "Product name successfully updated!"
      redirect_to admin_sub_category_path(@admin_sub_category)
    else
      flash.now[:error] = "Product name is not updated!"
      render 'new'
    end
  end

  def destroy
    @admin_sub_category.destroy
    flash[:notice] = "Product name is deleted"
    redirect_to action: :index
  end

  private
  def set_admin_sub_category
    @admin_sub_category = Admin::SubCategory.find(params[:id])
  end

  def admin_sub_category_params
    params.require(:admin_sub_category).permit(:category_id, :name, :identifier)
  end
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/views/admin/sub_categories/_form.html.erb
<%= form_for(@admin_sub_category) do |f| %>
  <% if @admin_sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_sub_category.errors.count, "error") %> prohibited this admin_sub_category from being saved:</h2>

      <ul>
      <% @admin_sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :category %><br>
      <%= f.collection_select(:category_id, Admin::Category.all, :id, :name_cat, :prompt => "Select Category") %>
    </div>

    <div class="field">
      <%= f.label :product %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :identifier %><br>
      <%= f.text_field :identifier %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/sub_categories/edit.html.erb
<h1>Editing Admin Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_sub_category %> |
<%= link_to 'Back', admin_sub_categories_path %>

app/views/admin/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Sub Categories</h3>
<%= link_to 'New Sub category', new_admin_sub_category_path %>
<table class = "table table-bordered table-striped" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Product</th>
      <th>Identifier</th>
      <th>ID Category</th>
      <th>Category</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_sub_categories.each do |admin_sub_category| %>
      <tr>
        <td><%= admin_sub_category.id %></td>
        <td><%= admin_sub_category.name %></td>
        <td><%= admin_sub_category.identifier %></td>
        <td><%= admin_sub_category.category_id %></td>
        <td><%= Admin::Category.find(admin_sub_category.category_id).name_cat %></td>
        <td><%= link_to 'Show', admin_sub_category %></td>
        <td><%= link_to 'Edit', edit_admin_sub_category_path(admin_sub_category) %></td>
        <td><%= link_to 'Destroy', admin_sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/sub_categories/new.html.erb
<h1>New Admin Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sub_categories_path %>

app/views/admin/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @admin_sub_category.category_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_sub_category.name %>
</p>

<%= link_to 'Edit', edit_admin_sub_category_path(@admin_sub_category) %> |
<%= link_to 'Back', admin_sub_categories_path %>