config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :api_translators
  end
  namespace :admin do
    resources :configuration_identifiers
  end
  namespace :admin do
    resources :currencies
  end

  devise_for :users

  post 'configurator/ids=:ids', to: 'configurator#items_to_cart'

  get 'configurator', to: 'configurator#configurator'

  get 'configurator/show_offer/offer_products=:offer_products', to: 'configurator#show'

  resources :order_items, only: [:create, :update, :destroy]

  get 'cart/sale_id=:sale_id', to: 'carts#sale'

  resource :cart

  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :sales

    controller :product_features do
      get 'product_features/product=:product', to: 'product_features#index'
      get 'product_features/product=:product/page=:page', to: 'product_features#index'
      resources :product_features
    end

    resources :extract_xmls do
      post :extract_xml_file, on: :member
      post :update_products, on: :member
      get  :delete_all_products, on: :collection
    end

    get '', to: 'admin#admin'
    get '/:product', to: 'products#index'

    resources :products
  end

  resources :store_mcomputers

  controller 'store_mcomputers' do
    get '/search/', to: 'store_mcomputers#list'
    get '/product=:product', to: 'store_mcomputers#list'
    get '/product=:product/filter=:filter', to: 'store_mcomputers#list'
    get '/product=:product/page=:page', to: 'store_mcomputers#list'
  end

  root 'store_mcomputers#store_mcomputers'
end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  validates :name_cat, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  def index
    @admin_categories = Admin::Category.all
  end

  def show
  end

  def new
    @admin_category = Admin::Category.new
  end

  def create
    @admin_category = Admin::Category.create(admin_category_params)
    if @admin_category.errors.empty?
      redirect_to admin_categories_path(@admin_category)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @admin_category.update(admin_category_params)
    if @admin_category.errors.empty?
      redirect_to @admin_category
    else
      render :edit
    end
  end

  def destroy
    @admin_category.delete
    redirect_to action: 'index'
  end

  private
    def set_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    def admin_category_params
      params.require(:admin_category).permit(:name_cat, :view_cat)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(@admin_category) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_cat %><br>
    <%= f.text_field :name_cat %>
  </div>
  <div class="field">
    <%= f.label :view_cat %><br>
    <%= f.number_field :view_cat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>
<%= link_to 'Show', @admin_category, class: "btn btn-primary" %> |
<%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Category', new_admin_category_path, class: "btn btn-primary"  %>
<h3>Listing Admin Categories</h3>

<table class = "table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name cat</th>
      <th>View cat</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_categories.each do |admin_category| %>
      <tr>
        <td><%= admin_category.name_cat %></td>
        <td><%= admin_category.view_cat %></td>
        <td><%= link_to 'Show', admin_category %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
        <td><%= link_to 'Destroy', admin_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/categories/new.html.erb
<h1>New Admin Category</h1>
<%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
<%= render 'form' %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_admin_category_path(@admin_category), class: "btn btn-primary" %> |
<%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
<p>
  <strong>Name cat:</strong>
  <%= @admin_category.name_cat %>
</p>

<p>
  <strong>View cat:</strong>
  <%= @admin_category.view_cat %>
</p>